---
title: Click Click Bank Bank
baseURL: "/"
params:
  palette: blue
  header:
    title: ClickClickBankBank
    logo_img: "/images/ccbb_land_740.png"
    has_nav: true
    menu:
      actions:
      - label: DÃ‰MARRER
        url: https://app.clickclickbankbank.com/sign-up
  footer:
    logo_img: "/images/ccbb_land_740.png"
    tagline: Amazon Affiliate Links Monitoring Tool
    has_nav: true
    nav_title: Company
    has_social: true
    social_title: Community
    has_subscribe: false
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    content: "&copy; ClickClickBankBank. All rights reserved."
    links: []
disableKinds:
- RSS
menu:
  main:
  - url: https://clickclickbankbank.com/
    name: "|  EN  | "
    weight: 5
